# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ce026067e1a5352bc28361b2640380cc7a9d938ada38f4f9dce1d9a18ea19a90eddbca9e4d1d76f0dc545f207babe43c0d1ed341eaedb8d8af14a70110341f8

test:
  secret_key_base: ccf82667071bfb870cd9cf10e8266c3640b4a95aa18ba92668e337f28df907293f8975ff0a7dbc7dc3ad7974b2c875d8dea0fbab25a10b0a918e45440b2643d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
